### ISSUE TITLE
Adopt pytest month

### ISSUE THREAD

**Issue by nicoddemus** [jsonpickle/jsonpickle#123]
Hi there,

In April the pytest team is holding "adopt pytest month" to encourage projects to consider using pytest, by pairing open source projects with experienced pytest helpers. I see your test suite is fairly complete and uses xUnit. Perhaps you would like to try to convert some/all of your tests with the help of on of our pytest volunteers (myself included)? Since pytest can run standard xUnit tests, you can convert tests to use the full power of pytest in any pace you like.

Anyway, there are no strings attached. :smile:

Take a look at http://pytest.org/latest/adopt.html if you're interested!

Cheers,

**Comment by davvid** [comment]
I don't know much about pytest so this is interesting to me. My current testing workflow for jsonpickle is running `tox --develop` and `tox --develop -e flake8`.

If you trace through the `tox.ini` the command that's eventually run is `nosetests --with-doctest jsonpickle . {posargs}`. This lets us do stuff like `tox ... --stop` and the `--stop` flag will be passed down as `nosetests --stop`.

My understanding is that `nosetests` does discovery of tests, so it's possibly a little slower than running `./tests/runtests.py` where all of the suites are (painfully) hand-wired.  I run that script as well sometimes when e.g. debugging a specific python version.

Orthogonal to the tox setup, which does its own thing under `.tox/`, I also keep virtualenvs around for python 2.6, 2.7, 3.2, 3.4 which are used for running the test suite both under nose and directly via `tests/runtests.py`.

I think I recently ran a pytest-enabled script for debugging an issue and it descended into the virtualenv `env32`, `env27`, `env*` directories and ran the tests in there, which was unintended. Do you know if there's a way to add exclude directives (kinda like the `.gitignore` stuff we have for `/env*`) so that pytest knows not to descent into those directories? I may have just been imagining that, though.

Maybe pytest can replaceme both nose and the hand-written `tests/runtests.py` in this workflow?

I'm especially interested if it can make the test runs faster.  Thank you for your help, it's much appreciated!

**Comment by nicoddemus** [comment]
Well, about tox integration there's no problem there (tox was created by pytest's creator, Holger Krekel). :smile:

Test discovery speed should be about the same in nose and pytest, but if your concern is about running the test suite during development, pytest also has some excellent filtering options that you can use in the command line (for example, `py.test -k datetime` will run only tests with have `"datetime"` on module, file or test name). Plus there's a lot of plugins to try out:

* [pytest-stepwise](https://pypi.python.org/pypi/pytest-stepwise) allows to run the test suite until the first test fails; when executing again, start from the last failed test and onward until a new test fails, and so on until the whole suite finishes. 
* [pytest-instafail](https://github.com/jpvanhal/pytest-instafail) allows to display failure tracebacks while the test suite is running, instead of only at the end.

This is just a few examples from the top of my head.

Also, you can configure pytest to do not descend into certain directories via a configuration file, so that's not a problem.

> Maybe pytest can replace both nose and the hand-written tests/runtests.py in this workflow?

Sure! 

> I'm especially interested if it can make the test runs faster. 

If the problem is test run time, we can try distributed testing (`nose` has support for it too); about test collection we will have to see.

pytest has a lot more to offer too, but don't worry, the objective of this movement is exactly to bring awareness to people who haven't look into pytest yet. :smile:

Please let this issue open because we plan to contact you through here when we start working next month.

Cheers! :beers:

**Comment by aldanor** [comment]
@davvid I've been using pytest / tox for all my project / work projects for a few years now. When I was working on numpy handlers, I considered porting jsonpickle test suite to pytest, but thought it would be a bit intrusive. 

I guess I could probably help with this :)

// the main benefit you would get out of pytest would be cleaner syntax, parameterized tests, function/module/class-level fixtures, smarter discovery etc.

If pytest is descending into folders you don't like it to touch, you tell it not to do it. In fact, most test tools these days look at `tox.ini`, so you could just add a section in there like

```ini
[pytest]
python_files = test_*.py
norecursedirs = ev32 env27 env*
```

**Comment by marcintustin** [comment]
@davvid This is probably an obsolete issue now. Much as I still like pytest, unless we seriously want to change up the style of tests, it's probably worth just sticking with what we have.
