### ISSUE TITLE
jsonpickle fails for hd5 data

### ISSUE THREAD

**Issue by jasonzliang** [jsonpickle/jsonpickle#143]
I am trying to to serialize some raw bytes from a hd5 file with jsonpickle and I noticed what I get after decoding is not the same as what the original data was before encoding. I am using jsonpickle 0.93 from the pypi repository. Please see the example below:

import jsonpickle
orig = "\x89HDF\r\n\x1a\n\x00\x00\x00\x00\x00\x08\x08\x00\x04\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xffh\x848\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00`\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x88\x00\x00\x00\x00\x00\x00\x00\xa8\x02\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00"
encoded = jsonpickle.encode(orig)
decoded = jsonpickle.decode(encoded)
print orig == decoded #prints False

This does not happen when using regular pickle:

import cPickle as pickle
encoded = pickle.dumps(orig)
decoded = pickle.loads(encoded)
print orig == decoded #prints True

**Comment by davvid** [comment]
Interesting, I've never tried serializing raw bytes. jsonpickle likely assumes a stringy posture, and because it goes to json, is likely forcing utf8 somewhere.

The simplest way to support this would be a custom handler for `bytes` that base64 encodes/decodes the value.

From the user's POV we could provide it as an extension like we do for numpy.
The usage would look like...

```
import jsonpickle.ext.raw
jsonpickle.ext.raw.register_handlers()
```

We should turn your bytestream above into a unit test.

**Comment by davvid** [comment]
Actually, it looks like we already have a code path to handle bytes, but we're using the quopri quoted-printable encoding and it's not handling this.. looking at the bytestream closely I see one spot where a `\n` became `\r\n`, which I still cannot explain.

Swapping the encoder out for b64 looks like it's the  simplest solution.
