### ISSUE TITLE
BSD vs. GPL

### ISSUE THREAD

**Issue by pkaeding** [jsonpickle/jsonpickle#172]
Hi

I see that you are declaring a BSD license in this project, but then depending on [jsonlib](https://launchpad.net/jsonlib), which is GPL licensed.

My understanding of GPL libraries is that if you depend on them, you need to release your code as GPL as well (even if you don't distribute the GPL library yourself). (IANAL, etc)

Any thoughts?

**Comment by johnpaulett** [comment]
jsonpickle neither depends upon jsonlib nor does jsonpickle install jsonlib as a dependency (see lack of `install_requires` in setup.py).

jsonpickle will use the builtin `json` library in Python or will use simplejson for older Python versions.

For user's convenience, if jsonlib is already installed by the user *and* the user selects jsonlib as the [preferred backend](https://jsonpickle.github.io/api.html#jsonpickle.backend.JSONBackend.set_preferred_backend), jsonpickle can swap from json/simplejson.

Since jsonlib is not a requirement for using jsonpickle, I believe we are sufficiently not "linking" to GPL code.  I will mark this issue as closed for now, though welcome other's thoughts.  

If @davvid has concerns still, I would suggest we remove the helper line that registers it as an option backend, `self.load_backend('jsonlib', 'write', 'read', 'ReadError')`, possibly moving it to the documentation as a suggestion on how to register jsonlib if the user prefers that backend.

**Comment by pkaeding** [comment]
Okay, thanks for the clarification. Fossa.io flagged this, and when I went to investigate, I saw `jsonlib` in the [requirements](https://github.com/jsonpickle/jsonpickle/blob/master/requirements-2.txt) file, so I thought it was a legit flag. It turns out it was another false positive!

Thanks!

**Comment by johnpaulett** [comment]
@pkaeding good to know about fossa.io and thanks for critically looking to make sure we are playing by the rules.

The requirements.txt file is used for development & testing, but does not define what is distributed for this project.
