### ISSUE TITLE
Jsonpickle apparently not working with local classes

### ISSUE THREAD

**Issue by mcondarelli** [jsonpickle/jsonpickle#185]
Hi,
I'm trying to use jsonpickle to serialize some mixed objects.
It is not working for me (or I didn't understand how to use it, of course).

I am using an up-to-date debian9 machine with python-3.5.3 and jsonpickle-0.9.3 .

My simple test program is (after cutting down all useless crap):
```python
import jsonpickle

def test():
    class MyClass(object):
        def __init__(self):
            self.value = 1
            self.name = 'foo'

    m = MyClass()
    print(m)
    f = jsonpickle.encode(m)
    print(f)
    o = jsonpickle.decode(f)
    print(o)

test()
```

I get the following output:
```
<__main__.test.<locals>.MyClass object at 0x7f5e792e39e8>
{"name": "foo", "value": 1, "py/object": "__main__.MyClass"}
{'name': 'foo', 'value': 1, 'py/object': '__main__.MyClass'}
```
While I expected something like:
```
<__main__.test.<locals>.MyClass object at 0x7f5e792e39e8>
{"name": "foo", "value": 1, "py/object": "__main__.MyClass"}
<__main__.test.<locals>.MyClass object at 0x###########>
```
What am I missing?

Thanks in Advance
/Mauro

**Comment by rlubke** [comment]
@mcondarelli If you move the class definition out of the function, it should work fine.

Quote from the top-level documentation:

> The object must be accessible globally via a module and must inherit from object (AKA new-style classes).

**Comment by davvid** [comment]
Yup, this isn't a use case we currently support.  It could be useful to extend the interface to allow users to provide an additional set of classes that can be used when reconstructing an object.

What would a good interface look like for that?  Is it better to overload `loads(...)` or is it better to add a separate method?

As a separate method, this relies on global state (the module-level unpickler we provide for convenience):
```
jsonpickle.register_classes(SomeClass, SomeOtherClass)
obj = jsonpickle.loads(...)
```

The low-level interface does not use global state:

```
unpickler = jsonpickle.unpickler.Unpickler()
unpickler.register_classes(SomeClass, SomeOtherClass)
obj = unpickler.decode(...)
```

Alternatively, we could extend the `loads()` API rather than having a separate method, and not have any state.  I slightly prefer this approach, despite the fact that `loads()` already has a lot of parameters:

```
obj = jsonpickle.loads(..., classes=(SomeClass, SomeOtherClass))
```

There are situations where classes are dynamic and can't always be made importable, so this would allow using jsonpickle in those environments.  Would extending the `loads()` function work for your use case?

**Comment by mcondarelli** [comment]
Thanks @davvid for your detailed explanation.

Yes, `loads()` extension would work in my case.
OTOH I already "solved" the problem by moving `class` at module level with no adverse effect.
I simply failed to realize `loads()` did not have access to class definition (my bad!).
