### ISSUE TITLE
Throw exception when target class is not defined

### ISSUE THREAD

**Issue by iFreilicht** [jsonpickle/jsonpickle#190]
When running `jsonpickle.decode()` and the target class denoted by `py/object` does not exist, a silent failure will occur. Quick demo:

```python
import jsonpickle

class Test:
    def __init__(self, i):
        self.i = i

frozen = jsonpickle.encode(Test(4))
print(jsonpickle.decode(frozen))
del Test
print(jsonpickle.decode(frozen))
```
Will output:
```
$ python3 demo.py
<__main__.Test object at 0x7f26fc6af780>
{'py/object': '__main__.Test', 'i': 4}
```
This makes troubleshooting hard when trying to access members of the class later. Normally something like this would occur when saving a file while running a module as a script and later trying to load that file while running a different script that only imports this module.

I propose an additional keyword argument to `decode()`, maybe `strict=False`. If this was set to true, an Exception should be thrown when [_restore_object()](https://github.com/jsonpickle/jsonpickle/blob/6a062399190f1f978b81f68471d2f284f80834f0/jsonpickle/unpickler.py#L143) can't find the specified class. [`NameError`](https://docs.python.org/3/library/exceptions.html#NameError) seems like a suitable one.

**Comment by jaraco** [comment]
I suggest instead of a boolean `strict`, have a parameter `on_missing`, which might be `"ignore"` (current behavior) or `"error"` (raise an exeception) or perhaps in the future a generic callable that takes missing object and handles it. In fact, maybe that's the best way to implement it to begin with: let `on_missing` always be a callable with the default being `lambda x: x` and the error option as a function that raises an error.

**Comment by iFreilicht** [comment]
So, looking at this some months later now, I would actually say that the default behaviour should be to throw a `NameError`. If you encode something, you expect the exact same thing to be returned when you decode it, and the `'py/object'` strings are implementation artifacts that should not be contained in the output.

Really, this would never ever happen unless the module you decode in is NOT the same that you encoded in and if you also forget to import the pickled class in your decoding module or if you import it as a different name, right?

Is there any use for the non-strict behaviour in the first place?

**Comment by jaraco** [comment]
> Is there any use for the non-strict behaviour in the first place?

Definitely.

When thinking about just a single object that you wish to encode/decode, there's little value in getting back an improper roundtrip.

But when thinking about more real-world use-cases, which may involve deep-nested hierarchies of possibly arbitrary objects, it's often desirable for the decoding to be lenient, returning the best-effort decoding, even if imperfect. Here are a couple of use-cases:

## Rollback

Consider an application that's using jsonpickle to store objects and the application is upgraded, adding a new class and instances of it in the serialized objects. The application is upgraded, storing some of these new objects, but then for whatever reason, the application needs to roll back to a prior version (where the class is not available). Being able to decode only the objects that were defined in the prior application version is worthwhile. Raising an error in this situation would require much more careful handling of the decoding.

## Hidden Classes

Consider the case where a class is defined outside of a reachable namespace:

```
>>> class A:
...   class B:
...     pass
...   def __init__(self):
...     self.b = self.B()
>>> jsonpickle.loads(jsonpickle.dumps(A())).b
{'py/object': '__main__.B'}
```

In this case, it may be more valuable to be able to successfully encode/decode the rest of A, even though B is not reachable.

## Partial Decode Useful

Often jsonpickle is useful for applications that may add arbitrary objects to a serialized object tree, but it's only important that some portion of those objects be retained for serialization (the other objects are perhaps discardable or incidentally part of the object tree).

---

I do agree with you that the strict behavior seems immensely valuable and maybe should even be the default behavior, but I would be surprised if there aren't some systems depending on the current behavior, and I can imagine some systems wanting to retain/enable this behavior.

**Comment by schperplata** [comment]
@jaraco Is at the moment any way to tell `jsonpickle` to raise exception/notify user that certain part of data can't be unpickled with appropriate Python data model (e.g. missing object definition)?

**Comment by jaraco** [comment]
Off the top of my head, I'm not aware. I'd not be surprised if there is a "fallback" behavior that could be customized or hacked to catch this situation. I'd recommend to dig into the implementation and explore what avenues might be possible. I wish I had better advice.

**Comment by schperplata** [comment]
As this is a real issue in our case, we (our company) are thinking of offering to invest some time in ithe mplementation - as long as we have some confirmation that it will be included in a release once done and reviewed. Of course, we would first need to know and agree on what is the expected behaviour. 

There already were a couple of suggestions by @davvid [here](https://github.com/jsonpickle/jsonpickle/issues/313#issuecomment-748707863). To wrap up, he is suggesting:
> I am suggesting {ignore,warn,strict} since the ignore and strict values are similar to string.decode(..., errors='strict') string API.

I also like the @jaraco [idea](https://github.com/jsonpickle/jsonpickle/issues/190#issuecomment-417706811) idea with error handler function:
>  ... let `on_missing` always be a callable with the default being `lambda x: x` and the error option as a function that raises an error.

Maybe the solution is somewhere in between, I am not really sure. Our specific use case is relatively simple (just raise any kind of exception on missing definition), but as jaraco described above, there are other use cases where this is not an option. 
What about `on_missing` that could receive `Literal["error", "warning", ignore"]` or 'Callable[]`?

**Comment by Theelgirl** [comment]
> What about on_missing parameter that could receive Literal["error", "warning", ignore"] or Callable[] (error handler)?

I'd be able to help implement this if it could take a callable function in addition to one of those three string literals.

**Comment by Theelx** [comment]
Currently working on this, and I'm planning to set on_missing to "ignore" by default, at least for jsonpickle 2.x.x (we could switch to "error" come 3.0). Any objections?

**Comment by davvid** [comment]
Sounds great to me, thank you so much again!
