### ISSUE TITLE
Preserve order when pickling

### ISSUE THREAD

**Issue by lmannering** [jsonpickle/jsonpickle#193]
I would like to preserve the order of dict when pickling objects. Is this possible? It seems that L432 in pickler.py currently forces alphabetical ordering:
    
`for k, v in sorted(obj.items(), key=util.itemgetter):`

Thanks for a really great package!

**Comment by marcintustin** [comment]
Dicts are not ordered, unless you're working with an ordereddict. If you're seeing this behaviour with ordereddict, please provide a test case.

**Comment by lmannering** [comment]
A simple example:
```
test = {'b': {'c': {'z': 1, 'a': 2}}}
print(test)
print(jsonpickle.encode(test, unpicklable=False))
```

```
{'b': {'c': {'z': 1, 'a': 2}}}
{"b": {"c": {"a": 2, "z": 1}}}
```
jsonpickle v0.9.5

**Comment by zach-nervana** [comment]
it is because the inner dictionaries are not `OrderedDicts`.

**Comment by davvid** [comment]
@lmannering please take a look at 7075b7ba5a999c9a74f11745a64afafa8569907c it demonstrates how to use OrderedDict with jsonpickle.  Let me know if you have any questions.  As others noted here, you have to construct OrderedDict using a list-of-tuples like the test case does otherwise the order is undefined (because it goes through a temporary python `{...}` dict that does not preserve order)..

We did have a bug when using `unpicklable=False` but that's now been fixed -- thanks for the heads-up!

That said, you probably don't want to use that flag ~ I'm guessing it was used while trying to debug this issue, perhaps?  In any case, it should be better behaved all-around.  The regular/default `unpicklable=True` code path was unaffected and was already working as intended.

**Comment by lmannering** [comment]
Thanks all, I'll check it out!

**Comment by lmannering** [comment]
Thanks for your comment @davvid. Sorry to be a pain, having looked at the code a little more, I can't seem to preserve order whilst unpicklable=False. It seems my issue isn't around dicts/ordereddicts, but around persistence of list order.

Running jsonpickle.encode(filtered, unpicklable=False) returns

```
"tables": {  
      "DObjCat": {
         "columns": {
              "dec": {
                   "name": "dec",
                   "type": "column"
                },
                "zcataid": {
                   "name": "zcataid",
                   "type": "column"
                 },
            }
     }
```
but jsonpickle.encode(filtered, unpicklable=True) shows the true order (i.e., zcataid above dec):

```
"tables": {
                                                        "DObjCat": {
                                                            "py/state": {
                                                                "columns": {
                                                                    "py/reduce": [
                                                                        {
                                                                            "py/type": "collections.OrderedDict"
                                                                        },
                                                                        {
                                                                            "py/tuple": []
                                                                        },
                                                                        null,
                                                                        null,
                                                                        {
                                                                            "py/tuple": [
                                                                                {
                                                                                    "py/tuple": [
                                                                                        "zcataid",
                                                                                        {
                                                                                            "py/state": {
                                                                                                "name": "zcataid",
                                                                                                "type": "column"
                                                                                            }
                                                                                        }
                                                                                    ]
                                                                                },
                                                                                {
                                                                                    "py/tuple": [
                                                                                        "dec",
                                                                                        {
                                                                                            "py/state": {
                                                                                                "name": "dec",
                                                                                                "type": "column"
                                                                                            }
                                                                                        }
                                                                                    ]
                                                                                },
```

If I change L432 in pickler.py:
`for k, v in sorted(obj.items(), key=util.itemgetter):`
to
`for k, v in obj.items():`

I can run unpickleable=False and see:
```
"columns": {
    "zcataid": {
        "name": "zcataid",
       "type": "column"
    },
    "dec": {
       "name": "dec",
       "type": "column"
    },
}
```

Or am I missing something obvious (likely)? Thanks all :)

**Comment by HolmesSherlock** [comment]
I am facing the same issue.

**Comment by davvid** [comment]
The encoder, decoder, and json backend have an implicit handshake in that they must process dictionary entries in the same order, otherwise stuff breaks.  Thus, if you're overriding backend options you must use `sort_keys=True`.   A future version can work towards removing this restriction, but that's how it currently works.

`unpicklable=False` is a mode where we drop support for things that json can't represent, so it's going to be lossy, and is not our primary use case.

It looks like those objects are actually tuples.  I would expect them to come back as lists, with the same order.  Can you show me a code example showing your use case?  If you want  your use case to be forever supported, please add it to our test suite in `tests/object_test.py`.  I can only make bad guesses at best without a test case.

**Comment by y-mironov** [comment]
I try this:
```python
bottom = OrderedDict([('z', 1), ('a', 2)])
middle = OrderedDict([('c', bottom)])
top = OrderedDict([('b', middle)])
encoded = jsonpickle.encode(top, unpicklable=False)
print(encoded)
```
result is
`{"b": {"c": {"a": 2, "z": 1}}}`

how do i get this 
`{"b": {"c": {"z": 1, "a": 2}}}`
instead
`{"b": {"c": {"a": 2, "z": 1}}}`
 ?
Is it possible?

**Comment by davvid** [comment]
It's 2020, so it's worth an update here.

I have a change that eliminates the use of `sort_keys` and thus should preserve dict order, but it only works on python3.

The reason is that python3 changes the behavior of dict iteration, where we can now rely on the order being preserved, and you don't even need to use OrderedDict anymore.

@lmannering sorry for taking this long to realize this was possible pretty easily.  I'll push a commit shortly that closes this issue for reals.  I do like how small of a diff this turns out to be, and the tests all pass.
