### ISSUE TITLE
Inner Classes fail to properly encode

### ISSUE THREAD

**Issue by Mnuzz** [jsonpickle/jsonpickle#210]
I have a class Foo with an inner class (within Foo) named Bar, within module 'm'. When encoding the object, this is what would show up:
```{"py/object": "m.Bar" ...```

This causes decoding to fail, as a dictionary will be created instead of the object.

Perhaps this is what should appear in the json?
```{"py/object": "m.Foo.Bar" ...```

**Comment by davvid** [comment]
This is already supported, but unfortunately it only works under python3, where we have a `__qualname__` identifier provided by the language.

Without that, it's not really possible to implement support for these classes.  You can workaround it by making the class available at module scope, through an alias:

```
class Foo(object):
    class Bar(object):
        ...

Bar = Foo.Bar
```

The `Bar = Foo.Bar` workaround makes it work on python2, and is not needed on python3.

**Comment by davvid** [comment]
I just realized we have a really simple workaround, better than exposing a new global symbol (which might clash with existing symbols at module scope).

Instead of doing that, provide the `__qualname__` yourself for python2, and jsonpickle will pick that up.

```
class Foo(object):
    class Bar(object):
        __qualname__ = 'Foo.Bar'
```

Please try that out.  The only downside is that you might want to remove that line in the future if things ever move over to python3 fully.

jsonpickle itself will remain 2+3 compatible for the foreseeable future.

**Comment by AnnanFay** [comment]
Thanks davvid! Your reply pointed me in the right direction to solve my own issue.

This method turns out to be a good workaround if you move the location of your classes but still want to decode old files for backwards compatibility.

```python
class LocalClass:
    ... #implementation

class _LocalClass(LocalClass):
    __module__ = "old.location.of"
    __qualname__ = "LocalClass"

data = jsonpickle.decode(json_data, classes=[_LocalClass])
```
