### ISSUE TITLE
failure to roundtrip reducible iterators

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#216]
I'm using celery.schedule.ScheduleEntry from celery 3.x, and while jsonpickle will produce a pickle for it, when decoding, it produces a `listiterator` instead of a ScheduleEntry:

```
$ rwt -q 'celery<4' jsonpickle
>>> import celery.schedules, celery.beat, jsonpickle
>>> schedule = celery.schedules.crontab(0, 12)
>>> entry = celery.beat.ScheduleEntry(schedule=schedule)
>>> entry
<Entry: None None() <crontab: 0 12 * * * (m/h/d/dM/MY)>
>>> data = jsonpickle.dumps(entry)
>>> data
'{"py/object": "celery.beat.ScheduleEntry", "py/iterator": [{"py/tuple": ["app", null]}, {"py/tuple": ["options", {}]}, {"py/tuple": ["args", {"py/tuple": []}]}, {"py/tuple": ["kwargs", {}]}, {"py/tuple": ["schedule", {"py/reduce": [{"py/type": "celery.schedules.crontab"}, {"py/tuple": [0, 12, "*", "*", "*"]}, null, null, null]}]}, {"py/tuple": ["total_run_count", 0]}, {"py/tuple": ["task", null]}, {"py/tuple": ["name", null]}, {"py/tuple": ["last_run_at", {"__reduce__": [{"py/type": "datetime.datetime"}, ["B+IIGQ4kLwRAFw=="]], "py/object": "datetime.datetime"}]}]}'
>>> jsonpickle.loads(data)
<listiterator object at 0x10e9e66d0>
>>> list(_)
[(u'app', None), (u'options', {}), (u'args', ()), (u'kwargs', {}), (u'schedule', <crontab: 0 12 * * * (m/h/d/dM/MY)>), (u'total_run_count', 0), (u'task',None), (u'name', None), (u'last_run_at', datetime.datetime(2018, 8, 25, 14, 36, 47, 278551))]
```

**Comment by jaraco** [comment]
This object does pickle/unpickle correctly using the `pickle` module, as ScheduleEntry supplies a `__reduce__` method. Probably the issue is that jsonpickle is giving precedence to the `__iter__`, but it probably should give precedence to the `__reduce__`.

**Comment by jaraco** [comment]
I tried proving my suspicion with the following class, but jsonpickle handled it as expected:

```
class CustomObject:
  def __init__(self, a, b):
    self.a = a
    self.b = b
  def __iter__(self):
    return iter((self.a, self.b))
  def __reduce__(self):
    return self.__class__, (self.a, self.b)
```

**Comment by jaraco** [comment]
Ugh. I tried using the jsonpickle master instead of the 0.9.6 release, but it's even more broken. I'll file a separate ticket for that issue.

**Comment by jaraco** [comment]
Digging deeper, I find that any Iterator can't be reduced:

```
class CustomObject:
  def __init__(self, a, b):
    self.a = a
    self.b = b
  def __iter__(self):
    return iter((self.a, self.b))
  def __reduce__(self):
    return self.__class__, (self.a, self.b)
  def __next__(self):
    return next(iter(self))
```

Pickling an instance of object produces:

```
{"py/object": "__main__.CustomObject", "py/iterator": [1, 2]}
```

And deserializing that object produces a `list_iterator`.

This behavior seems wrong to me. What is the motivation behind [this code](https://github.com/jsonpickle/jsonpickle/blob/bde56ae7f1c68a9c1f1b61836f2e3aabcdfb6943/jsonpickle/util.py#L353-L380)?

**Comment by davvid** [comment]
To answer your question, I think the purpose of that code is to find cases where we don't want to call `__reduce__`, but whether it's any good is a different question.

The whole idea of jsonpickle is partially impossible, but hopefully we can evolve it to a point where it's at least on par with the regular pickle module.  When JP was first written, I didn't know very much about python or pickle protocols or any of that stuff, so it was written in a brute force, plow-through-it style.

Once example is how to handle circular references that can occur inside of tuples.  The whole proxy object thing falls flat on its face in light of things like immutable objects such as tuples.  But as a trick that works for a narrow range of valid objects, it's a neat hack.

I wonder if there's a way we could do without the whole proxy object hack for handling objects with back pointers and circular references.  The referencing thing is a challenge (and buggy in particular situations) because the assigned IDs are dependent on graph traversal order.  If we could somehow hash everything, maybe `id(...)` or something better, then we could fix that issue too by having a stable way to refer to objects.  The graph traversal order is why we have to sort the keys when traversing dictionaries.

It might also be necessary to traverse the graph and find the objects that are "leaf nodes" in the object graph.  Then we'd serialize those first, and then their parents, etc.  That would probably make it easier to handle object references.  Maybe `id(obj)` is good enough.  We'd then store all objects in a flat dict in the json output.  I wonder if we'd have to also store the traversed object IDs in the json file so that the decoder can know to restore objects in that same order.  Hmm.

Anyways, just some long ranty ideas I figured would be worth writing down in case it triggered any ideas.  Thanks again for the improvements, maybe these ideas are useful before settling on jsonpickle v1.0.  I've been really reluctant about that, heh.
