### ISSUE TITLE
IndexError explicitly restoring object with FixedOffset

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#246]
I have [this script](https://gist.github.com/8167498b51eff44d93d7c5af28a4dd8a), which if run with `pip-run` generates this output:

```
Collecting jsonpickle
  Using cached https://files.pythonhosted.org/packages/dc/12/8c44eabb501e2bc0aec0dd152b328074d98a50968d3a02be28f6037f0c6a/jsonpickle-1.1-py2.py3-none-any.whl
Collecting pymongo
  Using cached https://files.pythonhosted.org/packages/d7/ac/d2e324c1f9bcf653fa106785371a16b4709506a35b04948655de8b961a85/pymongo-3.7.2-cp37-cp37m-macosx_10_9_x86_64.whl
Installing collected packages: jsonpickle, pymongo
Successfully installed jsonpickle-1.1 pymongo-3.7.2
{"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+MBHRIJCAyakA==", {"py/reduce": [{"py/type": "bson.tz_util.FixedOffset"}, {"py/tuple": [{"py/reduce": [{"py/type": "datetime.timedelta"}, {"py/tuple": [0, 0, 0]}, null, null, null]}, "UTC"]}, {"_FixedOffset__name": "UTC", "_FixedOffset__offset": {"py/id": 2}}, null, null]}]]}
Traceback (most recent call last):
  File "bson-utc.py", line 20, in <module>
    restored = json.loads(doc, object_hook=unpickler.restore)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-3soo3ndy/jsonpickle/unpickler.py", line 147, in restore
    self._swap_proxies()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-3soo3ndy/jsonpickle/unpickler.py", line 165, in _swap_proxies
    method(obj, attr, proxy)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-3soo3ndy/jsonpickle/unpickler.py", line 100, in _obj_setvalue
    obj[idx] = proxy.get()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-3soo3ndy/jsonpickle/unpickler.py", line 92, in get
    return self._objs[self._index]
IndexError: list index out of range
```

This error is almost identical to #120, except that I'm not relying on the `jsonpickle.loads`, but am instead explicitly calling `Unpickler.restore` during a normal deserialization operation. I'm doing this because I also need to secondarily wrap the restored objects in another function during deserialization.

I've tried a couple of things:

- invoking `Unpickler._restore` instead of `.restore`, but that leaves an _IDProxy object as the tzinfo on the datetime object, which causes issues.
- invoking `Unpickler._restore` but also invoking `Unpickler._swap_proxies` after, but that results in the same error.

I suspect the issue is mainly a mismatch between the expected use of `restore` and `json`'s expectation for an `object_hook`, the former of which expects to restore all objects, including lists, but the `object_hook` is only called for objects... so references are missing for lists.

Can you think of a better way to hook into a JSON deserialization to invoke the Unpickler.restore behavior?

**Comment by jaraco** [comment]
I don't think the issue is due to handling of lists vs. objects. After inspecting `_restore` calls in the standard `jsonpickle.loads` behavior, I see that `Unpickler._obs` becomes:

```
[<jsonpickle.unpickler._Proxy object at 0x10e6dfb70>, <jsonpickle.unpickler._Proxy object at 0x10e24ec18>, datetime.timedelta(0)]
```

at the time that the `{"_Fixed__offset": {"py/id":2}}` is processed... and those first two proxy objects correspond to the `datetime.datetime` and `bzon.tz_util.FixedOffset` objects... but in a `json.loads` operation, those objects don't yet exist. The order in which objects are processed is different. `json.loads` uses postorder while `jsonpickle` uses preorder... and since the order of references is essential to reconstructing those references, what I'm trying to do is simply not possible in the general case (even though it works in practice for many objects).

The reason this isn't an issue for the higher level interfaces (encode/decode) is because those interfaces don't rely on hooks into the backend's traversal, but instead perform the encoding/decoding on complete Python objects, handling its own traversal.

I'm most likely going to want to find a better mechanism to achieve what I'm after.

**Comment by davvid** [comment]
The idea I've had floating around is that maybe jsonpickle could do something a little slower, but more robust, in that it could do a pre-pass over the object tree where it collects references and object dependencies, then a second pass would serialize objects inside-out, with the objects that have no dependencies first.  Cycle detection and breaking are an interesting challenge here.

Serialization order then becomes independent of the initial traversal order.  One idea on how to store it is:

```
{
    "__objects__": [
        {..},
        {..},
    },
    "self": 1,   # could this be implicit?
}
```


Lists would even end up as an object `{..}` to make that work.  Simple primitive types can stay primitives, but most fancy types would end up in the dependency-sorted objects list.

It'd be interesting if we could instead have a object dict, instead of list, but that brings in the problem of needing to store a list of keys to specify the sort order.

In that scheme we have a chance of being able to handle these edge cases.

I should delete the tests that make assertions about the json representation in prep for a v2 serializer.

Also, instead of trying to come up with my own idea, I should probably read the cpython pickle source code first and see how much we I can learn from reading that code.  We should also add test cases for things jsonpickle can do that pickle can't (are there any?), and vice versa.

Any other wild ideas for a better, more structured approach to serialization?

**Comment by mspacek** [comment]
In terms of something that jsonpickle can do that CPython pickle can't, it seems from my initial tests that jsonpickle can simultaneously serialize DateTime objects and numpy record arrays with string field names in Python 2, and successfully deserialize them in Python 3 without any unicode errors and the like. This bug report has some of the gory details:

https://bugs.python.org/issue6784

Here's a simple test, some of it might be superfluous:

```python
def get_data():
    import numpy as np
    import datetime
    dtype = [('x', np.uint16), ('y', np.float32)]
    arr = np.ones((2, 10), dtype=dtype)
    dt = datetime.datetime(2015, 10, 12, 13, 17, 42, 123456)
    data = {"ascii":"abc", "text":u"äbc", "intval":42, "arr":arr, "dt":dt}
    return data

## pickle:

## PY2:
import cPickle as pickle
data = get_data()
with open("pickle.test", "wb") as f:
    pickle.dump(data, f, protocol=-1)

## PY3:
import pickle
with open("pickle.test", "rb") as f:
    data = pickle.load(f) ## FAILS!
#UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 4: ordinal not in range(128)

## jsonpickle:

## PY2:
import jsonpickle
data = get_data()
with open("data.json", "w") as f:
    f.write(jsonpickle.encode(data))
>>> data
{'arr': array([[(1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.),
         (1, 1.), (1, 1.), (1, 1.)],
        [(1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.),
         (1, 1.), (1, 1.), (1, 1.)]], dtype=[('x', '<u2'), ('y', '<f4')]),
 'ascii': 'abc',
 'dt': datetime.datetime(2015, 10, 12, 13, 17, 42, 123456),
 'intval': 42,
 'text': u'\xe4bc'}

## PY3:
import jsonpickle
with open("data.json", "r") as f:
    data = jsonpickle.decode(f.read()) ## WORKS!
>>> data
{'arr': array([[(1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.),
         (1, 1.), (1, 1.), (1, 1.)],
        [(1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.), (1, 1.),
         (1, 1.), (1, 1.), (1, 1.)]], dtype=[('x', '<u2'), ('y', '<f4')]),
 'ascii': 'abc',
 'dt': datetime.datetime(2015, 10, 12, 13, 17, 42, 123456),
 'intval': 42,
 'text': 'äbc'}
```

**Comment by davvid** [comment]
@jaraco I managed to get this working by doing two things.

1. When calling the initial loads(), make sure you construct the Unpickler beforehand so that you can pass it as `loads(doc, context=unpickler)`

2. When calling restore, you may need to use `reset=False`.

I added a unit test in eb505c0 that demonstrates how to make this work.

A lot was recently improved related to dict ordering and how the ID offsets are handled, so it's worth taking another look since things may be better behaved (when using python3.6+ especially).

While I have your attention, I pushed an `isoformat` branch to my `git://gitub.com/davvid/jsonpickle.git` fork.  This is purely aesthetic, but in that branch I updated the json representation to make it just a tiny bit easier to read for humans.

Old format:
```json
{"py/object": "datetime.datetime",
 "__reduce__": [{"py/type": "datetime.datetime"}, ["B+MBHRIJCAyakA==", {"py/reduce": [{"py/type": "bson.tz_util.FixedOffset"}, {"py/tuple": [{"py/reduce": [{"py/type": "datetime.timedelta"}, {"py/tuple": [0, 0, 0]}]}, "UTC"]}, {"_FixedOffset__offset": {"py/id": 2}, "_FixedOffset__name": "UTC"}]}]]}

```

New format.  Still kinda noisy, but slightly more readable:

```json
{"py/object": "datetime.datetime",
 "iso": "2019-01-29T18:09:08.826000+00:00",
 "tzinfo": {"py/reduce": [{"py/type": "bson.tz_util.FixedOffset"}, {"py/tuple": [{"py/reduce": [{"py/type": "datetime.timedelta"}, {"py/tuple": [0, 0, 0]}]}, "UTC"]}, {"_FixedOffset__offset": {"py/id": 2}, "_FixedOffset__name": "UTC"}]}}
```

It's not a huge improvement, but if someone thinks it's worth tweaking I'd be in favor of merging that change in as well.  Let me know what you think, and hopefully the new testcase and the recent improvements help.
