### ISSUE TITLE
order of dicts coming from jsonpickle.dumps in Python 3.7.4 not preserved

### ISSUE THREAD

**Issue by mtopinka** [jsonpickle/jsonpickle#278]
Hi- thank you for putting out an extremely useful utility.  The problem I'm having is pretty much contained in the title.  I am using jsonpickle 1.2, Python 3.7.4.   Here is the code that will reproduce the bug:

```
import jsonpickle

dict_ab = {"a": 1, "b": 2}
dict_ba = {"b": 1, "a": 2}
print("print: (preserves dict order)")
print(dict_ab)
print(dict_ba)
print("\njson.dumps: (preserves dict order)")
print(json.dumps(dict_ab))
print(json.dumps(dict_ba))
print("\njsonpickle.dumps: (doesn't preserve dict order)")
print(jsonpickle.dumps(dict_ab))
print(jsonpickle.dumps(dict_ba))
```

and here is the output I get:

```
print: (preserves dict order)
{'a': 1, 'b': 2}
{'b': 1, 'a': 2}

json.dumps: (preserves dict order)
{"a": 1, "b": 2}
{"b": 1, "a": 2}

jsonpickle.dumps: (doesn't preserve dict order)
{"a": 1, "b": 2}
{"a": 2, "b": 1}

```

Am I doing anything stupid or not understanding anything here?  I've tried setting sort_keys to True or False with no effect.   Thanks in advance.  -Mark

**Comment by davvid** [comment]
That's expected behavior with dicts -- the iteration order is undefined and programs should not rely on it.  `sort_keys` sorts the keys, not the values, so seeing the keys in `a .. b` order is expected.

The iteration order can also influences the resulting encoded object, so jsonpickle normalizes to iterating over dict keys in a sorted order.

If you need to preserve insertion order then you need to use `collections.OrderedDict`, or use a different data structure.  I personally try to avoid using that class -- YAGNI, there's usually a simpler approach.

Also, python internally creates a random hash that can influence iteration order over dicts.  The regular dict makes no guarantees otherwise `OrderedDict` would not exist -- try increasing your sample size to a bunch of different strings beyond the tiny sample size of 2 and you might start seeing different results.  Try adding examples where you loop over the keys and see what happens across different python versions -- python 2, 3, and possibly between minor versions of 3.x will likely iterate in different order.

https://stackoverflow.com/questions/5629023/the-order-of-keys-in-dictionaries

Maybe in some distant future where 3.7 has been around for a decade we can start to rely on the new 3.7.x behavior where sort order is preserved, but until then, please use an ordereddict.

**Comment by mtopinka** [comment]
Hi davvid - thanks for the quick response.  I know prior to 3.7 this was true, but I thought as of 3.7 that dict order was actually well defined and supposed to be preserved?
