### ISSUE TITLE
jsonpickle goes out-of-memory while trying to de-serialize an object that wraps a huge JSON stream

### ISSUE THREAD

**Issue by holmessherlock** [jsonpickle/jsonpickle#284]
If a large JSON string is wrapped in an object instance, for some reason `jsonpickle` east up a lot of memory while de-serializing the object and eventually goes out-of-memory. Just to give an idea, if the JSON stream is ~3GB in size, `jsonpickle` goes out of memory (`MemoryError`) on a 32GB Ubuntu 18.04 system. Looks like it tries to parse the JSON stream while it doesn't need to, and that causes the memory explosion. Here is a minimal example that triggers this issue.

```
import jsonpickle

# A large input file in JSON format
INPUT = 'a_huge_json_file.json'

# Wrapper class
class MyObject:
    def __init__(self, data):
        self.data = data

if __name__ == '__main__':
    # Read the JSON input
    with open(INPUT, 'rb') as fp:
        data = fp.read()

    # Create an instance of the object that wraps the JSON stream
    obj = MyObject(data)

    # Serialize the instance
    obj_dump = jsonpickle.encode(obj)

    # De-serialize the instance
    obj_load = jsonpickle.decode(obj_dump)
    
    with open(output.json', 'wb') as fp:
        fp.write(obj_load.data)
```

**Comment by davvid** [comment]
We don't parse what we don't have to, because we don't parse anything.  All jsonpickle does is transform your objects into a json-friendly atomic types, dicts, lists, etc. and hand that off to whatever backend you're using, e.g. the stdlib `json` module, or `simplejson`.

Python is not really a great language if you're looking to limit memory usage, but nonetheless you can still hand-tweak some things to help you.  Beyond that, your best bet is to make sure you have swap enabled and use an ssd for your swap if that design is set in stone.

Firstly, after you've created `obj_dump`, you could for example `del obj` and `del data`, and then call `gc.collect()` to cleanup the original memory that you no longer need from those objects.

Afterall, you've just copied the original object into a json string, which by necessity must escape the huge json string you provided in the object.  By definition you've just asked for it to *at least* double your memory usage in that string, especially since all of the json `"` quotes are going to need to be `\"` escaped when stored as a json string value.

It'll use more memory, but if you intended to instead `json.load(fp)` data then you can avoid the json string having the ugly double-encoded json string `data` in the output, and your data would be available directly, but that's besides the point.

Anyways, after you've done `obj_load = ...` then you don't need `obj_dump` anymore either, so after that line you could also do `del obj_dump` and then garbage collect again.

Sorry, but you really haven't identified any actionable problems with the library that we can practically address, so I'm closing this issue.
