### ISSUE TITLE
Expecting value: Line 1 Column 62

### ISSUE THREAD

**Issue by Theelgirl** [jsonpickle/jsonpickle#296]
No matter what document I try to decode with jsonpickle.decode, I get this error:
`json.decoder.JSONDecoderError: Expecting value: line 1 column 62 (char 61)`
It happens in a different place with each document, sometimes occurring in the middle of a key, sometimes in a value, sometimes after a comma, but always at column 62, char 61. I'd include a screenshot, but I don't know how, I've never used GitHub much before.

Python 3.8.1
Tried on jsonpickle 0.9.5, 1.3, and the version cloned off GitHub.

**Comment by davvid** [comment]
Can you share some example code that triggers this behavior?  I haven't seen anything like this before so maybe it's something unique to the documents you're encoding.

Thanks for the report.  That's super interesting that it always has the same column.

**Comment by Theelgirl** [comment]
Yeah, sure!
`        player_data = {"py/state": loaded_player, "py/object": "dueutil.game.players.Player"}
        player_data["py/state"].update(other_loaded_player)
        player_data = json.dumps(player_data)
        try:
            loaded_player = jsonpickle.decode(player_data)
        except json.decoder.JSONDecodeError as e:
            print("1", id, str(player_data), str(e))
            return
`
I keep hitting the JSONDecodeError at column 62.

**Comment by davvid** [comment]
Not sure how you're producing this, but perhaps there's some bug in the stuff that's getting fed into your code.  I was hoping you could share the objects that originally were serialized.

In any case, this part of the json looks suspect:

```
"no_save": False"
```

The code that generated that json string is using False instead of `false`, and there's the problematic double-quote `"` right after `False` which is going to upset most json parsers.  If I had to guess, there's code that is munging the strings or doing something funky, and it's producing the invalid json and injecting it invalid json into the document verbatim.

Dig into whatever is producing the `no_save` value, as it's likely to be the culprit.

Please feel free to reopen if there's a bug in jsonpickle itself, or something that we can add to our unit tests to guarantee that your use case continues to work forevermore.  I was hoping you would provide some example code that we could add to our `tests/thirdparty_test.py` that demonstrates the problem, ideally in the form of a PR.

Are you able to run JP's unit tests?  If not, try `make test` if you already have pytest installed, or create a virtualenv, `pip install -r requirements-dev.txt` into it, and run `make test` in that environment.

Thanks for getting back, and please let me know if there's anything else we can do.

**Comment by davvid** [comment]
I just noticed another thing detail that'll bite you later -- valid json uses `false` verbatim, not double-quoted `"false"` so there's definitely something funky going on around either boolean values, or the code that's generating those json snippets.

Note how it says, `"benfont": "false",` -  It should be `"benfont": false,` instead.  That will parse just fine, though, but it'll manifest at runtime as boolean values that are instead strings `"true"` and `"false"`, and the super fun part is that both of those string values will evaluate to truthy values in python.

Any conditionals that use those values will evaluate to `True`, even when the value is `"false"`.
