### ISSUE TITLE
Doesn't respect @property

### ISSUE THREAD

**Issue by ExpDev07** [jsonpickle/jsonpickle#297]
Hey! When using ``jsonpickle.encode(Object)``, it doesn't serialize the methods marked with @property. For example:

```python
@property
def name(self):
    return 'John Smith'
```

Should yield the following json:
```json
{
  "name": "John Smith"
}

**Comment by ZENALC** [comment]
Not exactly sure what you mean, but I tried it with @property, encoded an object, decoded it, and it still works as expected.

**Comment by Sikiru98** [comment]
> Not exactly sure what you mean, but I tried it with @Property, encoded an object, decoded it, and it still works as expected.

so you fixed the issue ?

**Comment by cddumanov** [comment]
Nope, doesn't work for me. jsonpickler does not serialize properties for me.

**Comment by johnpaulett** [comment]
This is by design.  jsonpickle isn't serializing methods, which `def name` is.  The property "should" work again when you decode the json back via jsonpickle.  Even more complex properties that are computed from other data

```python
class MyObject:
   def __init__(self, first, last):
      self.first = first
      self.last = last

   @property
   def name(self):
      return f"{self.first} {self.last}"
```
Encoding will result in `first` and `last` JSON keys, but no `name` key.  When you decode this back into a MyObject, the `name` attribute will come in via the class.

**Comment by hieronymusma** [comment]
@johnpaulett Thank you for the clarification.
My use case is to have computed values also appear in the JSON.
```python
class MyObject:
    arr: List[int]

    @Property
    def arr_len(self) -> int:
        return len(arr);
```
I want to have `arr` and `arr_len` appear in the encoded JSON. I only use jsonpickle for encoding objects in JSON and use the JSON elsewhere (not in python). Is there any simple method to achieve what I want (instead of setting `arr_len` manually on every update on `arr`)? Thank you very much!
