### ISSUE TITLE
Any Recommendation for serialization between IronPython and cPython3

### ISSUE THREAD

**Issue by yck011522** [jsonpickle/jsonpickle#312]
Hello.

As a developer who use jsonpickle as a way to bridge between Python 2 (IronPython) and  Python 3 (cPython) code. I find that sometimes my objects are jumbled upon serialization.

My particular use case is when I serialize a custom object that I wrote in ronPython with `make_refs=True, keys=True` . 

If I deserialize this object in Python 3.7.6, the items that clearly had an `"py/id"` were all mixed up.

I wonder if the developers have tested a scenario where serialization between IronPython 2 and cPython 3, And if there are somethings that need to be aware of.

**Comment by yck011522** [comment]
This problem do not happen if I deserialize the said object in IronPython

**Comment by davvid** [comment]
Oh yeah, there is an edge case across the 2 vs. 3 barrier around how dictionary keys are sorted.  It started in py3.6 to be precise.

Anyways, long story short is that, yeah, the IDs will be in a different order due to the difference in object traversal.  The traversal / encoding strategy is something that could be improved.  In the library you'll see parts where we conditionally sort based on the older python version.

The newer versions do not sort when iterating over dicts, because dict key order is now preserved in python, and that is basically the hard part.

One thing that would work would be to tweak it to unconditionally sort.  The downside is that py3 loses its dict-preserving property, but it's all a trade-off.

There was a previous issue reported where the user wanted to preserve the dict order, and that's what led to the current behavior.  I wouldn't be opposed a patch that adds another boolean flag to opt-in to unconditionally sorting.

The function where we sort is `util.items(...)` and you'll see a few key places in `pickler.py` and `unpickler.py` where `util.items(...)` is used.

A quick hack for testing is to unconditionally set `PY3_ORDERED_DICT = False` in the `compat.py` and see if that gets it working.

**Comment by yck011522** [comment]
Thank you so much for your help. 

So if I understand it correctly, since I serialize in py2, the object dict is sorted on serialize and then written to disk. When I unpickle it in py2 again, since `PY3_ORDERED_DICT = False`, the deserialization works as expected. However, if I unpickle it in py3, `PY3_ORDERED_DICT = True`, the result is scrambled.

For the quick hack test you suggested is it okay if I force `jsonpickle.util.PY3_ORDERED_DICT = False` after `import jsonpickle`? Or do I have to change `compat.py` in the installed source.

**Comment by yck011522** [comment]
I have trouble reproducing the error in my code, probably because my dependency library updated some code and now its not triggering the problem. I'll investigate further and get back.

**Comment by davvid** [comment]
For the quick hack it unfortunately requires changing `compat.py` in the source because other modules import that symbol directly.  There are also some early decisions about whether to initialize the backend with `sort_keys=True` that necessitate changing it at that level.

**Comment by yck011522** [comment]
@davvid Thanks. I'm still trying to reproduce my error with no luck. But if I do, I'll try your hack and report back. I'll close this issue for now and reopen if I can find something.
