### ISSUE TITLE
future builtins str pickles to py/newargs

### ISSUE THREAD

**Issue by optinirr** [jsonpickle/jsonpickle#319]
This piece of code shows how the the acceptable python 2 to 3 port of unicode to str isn't compatible with jsonpickle.encode: 
```
import future
from jsonpickle.pickler import encode
from builtins import str

r = str("abc")
print(encode(r))
```
results in an object instead of string

```
{"py/newargs": {"py/tuple": ["abc"]}, "py/object": "future.types.newstr.newstr"}
```

**Comment by davvid** [comment]
"acceptable python 2 to 3 port" is subjective, and I have real-world working examples that eschew such practices. I guess I'll add this to my checklist of reasons why I avoid the `future` module for library and application code.  Thank you for putting the final nail in the coffin for me.

Wouldn't it be better to just rely on the stdlib?

```
from __future__ import unicode_literals
```
and avoid the `str(...)` operator full-stop.  Do you need to do `str("abc")` -- how about just `"abc"`.   Why do we need to make things complicated?

Once again, the good design of any python application will have a pure unicode core, and only the outer boundaries of the system (files, IO) should need to deal with encoding to bytes.  All of the "benefits" of the "newstr" type are pointless when you follow this design.

What benefits do we get from the `future.types.newstr.newstr` type from the `future` module provide?  I'm asking because I'm too lazy to look it up, but also because I don't really think there's a benefit, or at least one that's worth the mental overhead and added complexity.

This is working as designed.  The library is being given a (weird) custom type, and jsonpickle is preserving that type.  Wouldn't it also be a bug if we did a roundtrip encode/decode cycle and it *lost* the underlying `future.types.newstr.newstr` type?

If we pickled to a regular string then there'd be a differnt bugreport saying that `builtins.str` from `future` is unpickling to the wrong type.

I really *really* __really__ don't understand the purpose of that `future` `str` thing, so please pardon my blissful ignorance.  It's totaly xkcd/927 from my simple-minded perspective.  We already have enough string types, why should we make things even more complicated by having a custom string type?

End of rant.  Sorry, there's nothing more to be done here, except to stop using a custom type.

That said, if you'd like to perhaps contribute a `jsonpickle.ext.future` extension module similar to what we have for pandas and numpy that serializes these weird strings as if they were normal strings, then please feel free to re-open this issue and submit a PR with that, but otherwise this is basically working as intended.

That module would have the caveat I listed above -- it's going to lose the underlying `newstr` type, but, hey, it's trade-offs all the way down.

**Comment by optinirr** [comment]
You're absolutely right - to the point where I had to forego the entire future library and use different methods to port my code.

Just to complete where I'm coming from, I have 5 years of Python Legacy code to port, and I don't have the convenience of choosing what type of unicode, str or any other types are used as the code is full of years of developer abuse. My hope to run the "futurize" and having things work out of the box died together with this integrational issue.

anyway, thanks for your time!

**Comment by davvid** [comment]
I do feel your pain. We have a huge wall of python code to port to 3 as well, so I'll at least say that jsonpickle intends to be python2+3 compatible and not get in the way of any cross-version porting efforts.

Since this custom type does exist, and it's a common type, one idea is we could provide a custom handler that encodes it to a (slightly) nicer-looking representation, but it won't ever be as simple as a normal string, unfortunately.

Here are some examples for discussion.  https://github.com/git-cola/git-cola/ was made compatible pretty early, so it originally was 2.6 + 3.4+ compatible.  `futurize --stage1 --all-imports --unicode-literals` would have been nice to have used at the time as a great jumping-off point since it nudges things towards the "unicode core" python3-style design.

The current 2.7+ code base managed to keep most of the compat code and stdlib wrappers relegated to two modules -- `cola.compat` and `cola.core`.  Then everything uses stuff from the app-specific compat modules to paper over the python  version differences.

The "unicode core" approach worked well for cola, which is a PyQt4 + PyQt5 compatible, Python 2+3 compatible, internationalized, unicode-aware, Linux, macOS, and Windows-compatible desktop application.

I wish there was a way to get futurize to emit `from __future__ import absolute_import, division, print_function, unicode_literals` as a single line at the top of every file instead of adding each import one at a time, but I guess automation is more important than aesthetics.  We ended up doing it manually at the time, but futurize seems perfect for that despite the extra lines.

Curious, what guides have you been following?  I'm sure you know about the "Conservative Python3 Porting Guide", and am curious if that's becoming a common strategy for those with long-living code bases that will need to keep compatibility for a little while longer.

A 2+3 compat port is tricky because you may inevitably end up touching every file, but the upside is you can keep running in both environments for a long time to prove things out.  The downside, though, is that a python3-only code base is intrinsically different from a 2+3 code base, and we have to hold our appetite for python3-only features that we are not allowed to use.

The other nice thing about a compat module is that you can later grep for its usage and swap over to using python3-only constructs when the day arrives that we can finally drop 2.7.

For cola, I made the decision that maximum compatibility for the benefit of users made the most sense despite the development overhead of having to support multiple versions.  If your production environment has only ascii data then you may find that a lot of the code will work just fine after that first stage, and will only need minor tweaks for py3 compatibility.

I'm curious, are you using the `six` module?  My observation is that you can get pretty far with just `six` and/or some custom compat wrappers.  There's nothing wrong with `if PY2:` checks as needed IMO, as long as it's kept tucked away somewhere tidy rather than sprawling over the entire codebase.

Getting tests running in both versions is the key part.  `tox` continues to be key to that for many projects (jsonpickle included).

`pylint --py3k` is pretty helpful too.  Those are my gotos.  

Let me know what else you've considered as part of the python3 porting effort; it's a topic I enjoy hearing about if you're able to share more details.

**Comment by optinirr** [comment]
I'm following that guide as much as possible yes, and the testing is crucial and it helped me weed out most of the "futurize" related issues - mostly surrounding the object, next and unicode problems, but the script is still useful for a lot of simple changes, like iteritems, tuples, except, etc.

Ammusingly, event the simple changes like long -> int don't work properly - it naivly replaces function arguments like get_geo_point(lat=None, long=None) to get_geo_point(lat=None, int=None) - another word of caution for all developers: never use code language for variables or member names: next, filter, long, etc, All of these appeared in our code and are being obliterated by the automated tool.

We've actually split our code base to 3 parts: A 2&3 package , a 2 only legacy code which will probably stay like that for years, and code that will be modernized to 3 in the near future. This strategy helped divide and conquer - but also it makes much more sense for us to use the "past" library so that the legacy code in 2 will not break while we actively work on modernizing the rest.

Additionally, I run the automated tools, then the tests, then fix the code in a way that I can run the automation without destroying the code (like change long to geo_long, filter to point_filter), and rebase the automation changes on top of that. Then I have atomic PRs which don't include the automation and get me "automation ready". I also fashioned a script that allows me to mark certain lines as "SKIP AUTOMATION" - which also helps in certain issues.

I'm using six mainly for the unicode issues, which we have a lot of because i18n of our application.  Like you said, most of the gritty work is isolating the string wrangling to a few functions and handling the porting there. 

Haven't started the py3 linting yet, maybe I should - I'll give that a try.
