### ISSUE TITLE
change website link in about page

### ISSUE THREAD

**Issue by arpitkaushal** [jsonpickle/jsonpickle#359]
use `jsonpickle.github.io` instead, `jsonpickle.github.com` gives 404 status

**Comment by davvid** [comment]
@johnpaulett this is one of those things that I'm unable to edit since I'm not an "owner" of the repo/org (just a "member"). I also can't add other maintainers and manage other repository details (eg. the default branch on github) which I was going to do a while back but since I couldn't so I left it as-is. Renaming the `jsonpickle.github.com` repo to `jsonpickle.github.io` was something else I wanted to do in the past.

I was interested in adding some of our past contributors as maintainers to increase the bus factor in the past. Even though I may think that some of the things jsonpickle tries to do is a bit wild / best-not-done (or maybe impossible), I do intend to at least keep things working so as to not break existing users.

Thanks again!

**Comment by johnpaulett** [comment]
@davvid You have updated permissions to proceed.

**Comment by davvid** [comment]
Thanks for the report and the updated perms.
