### ISSUE TITLE
jsonpickle works when invoked from shell, but not within PHP?

### ISSUE THREAD

**Issue by MichaelSternNYC** [jsonpickle/jsonpickle#367]
I have found that if PHP calls a python program that has the line 'import jsonpickle', the python program will not run, even if (a) the python code runs fine with this line commented out, (b) the python code (with jsonpickle) runs fine when invoked from the shell, and/or (c) jsonpickle is never actually used after being imported.

It's very odd.

**Comment by Theelx** [comment]
Can you provide a minimal reproducible example for this? Specifically, these would be helpful:
- The name and specific code for whatever tool you use to call a python program from php
- The python code
- Any relevant log files
- And, the versions of python, jsonpickle, and php you're using
I'm very suspicious that jsonpickle is the cause of the problem, because you said the problem exists even if the ``import jsonpickle`` line os commented out. To me, it sounds more like an issue with the tool for calling python from php, as in maybe it removes hashtags and leaves the line following in place?

**Comment by MichaelSternNYC** [comment]
I ultimately solved this by 'sudo' installing jsonpickle on top of the normal installation. Shrug.
