### ISSUE TITLE
`unpicklable=False` when using the NumPy handlers

### ISSUE THREAD

**Issue by stefan6419846** [jsonpickle/jsonpickle#381]
I am currently having trouble to understand what `unpicklable=False` really means. The docs have not been clear enough for me.

Background: I want to serialize custom objects into a JSON structure. As this is just for dumping output data (list and dictionaries of custom objects) and I perform further processing outside of the original application, I always set `unpicklable=False` to reduce the general overhead in the output.

Now I discovered that NumPy data types where rendered as `"key": {"py/newargs": [123.456]}` despite setting `unpicklable=False`. Activating the NumPy extension module of *jsonpickle* will produce `"key": {"dtype": "float64", "value": 123.456}` instead. With `unpicklable=False` I would have expected to just get `"key": 123.456` - at least when activating the NumPy support. To achieve this it seems like I have to write a custom handler.

Is this a bug or a feature and I am getting something wrong here?

Example code:

```python3
import jsonpickle
import numpy as np
from jsonpickle.ext import numpy as jsonpickle_numpy


class User:
    def __init__(self, username, user_id, score):
        self.username = username
        self.user_id = user_id
        self.score = np.array([score], dtype='float')[0]


users = [
    User('test1', 1, 1.23456),
    User('test2', 2, 123.456),
]

print('=== Without explicit NumPy support ===')
print(jsonpickle.dumps(users))
print(jsonpickle.dumps(users, unpicklable=False))
print()

jsonpickle_numpy.register_handlers()

print('=== With default NumPy support ===')
print(jsonpickle.dumps(users))
print(jsonpickle.dumps(users, unpicklable=False))
print()


class NumpyGenericHandler(jsonpickle_numpy.NumpyGenericHandler):
    def flatten(self, obj, data):
        if not self.context.unpicklable:
            return self.context.flatten(obj.tolist(), reset=False)
        else:
            return super(NumpyGenericHandler, self).flatten(obj, data)

    def restore(self, data):
        raise NotImplementedError


jsonpickle_numpy.register(np.generic, NumpyGenericHandler, base=True)

print('=== Custom NumPy support respecting `unpicklable` state ===')
print(jsonpickle.dumps(users))
print(jsonpickle.dumps(users, unpicklable=False))
```

Corresponding output:

```
=== Without explicit NumPy support ===
[{"py/object": "__main__.User", "username": "test1", "user_id": 1, "score": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/reduce": [{"py/type": "numpy.dtype"}, {"py/tuple": ["f8", false, true]}, {"py/tuple": [3, "<", null, null, null, -1, -1, 0]}]}, {"py/b64": "ODKP/MHA8z8="}]}]}}, {"py/object": "__main__.User", "username": "test2", "user_id": 2, "score": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/id": 3}, {"py/b64": "d76fGi/dXkA="}]}]}}]
[{"username": "test1", "user_id": 1, "score": {"py/newargs": [1.23456]}}, {"username": "test2", "user_id": 2, "score": {"py/newargs": [123.456]}}]

=== With default NumPy support ===
[{"py/object": "__main__.User", "username": "test1", "user_id": 1, "score": {"py/object": "numpy.float64", "dtype": "float64", "value": 1.23456}}, {"py/object": "__main__.User", "username": "test2", "user_id": 2, "score": {"py/object": "numpy.float64", "dtype": "float64", "value": 123.456}}]
[{"username": "test1", "user_id": 1, "score": {"dtype": "float64", "value": 1.23456}}, {"username": "test2", "user_id": 2, "score": {"dtype": "float64", "value": 123.456}}]

=== Custom NumPy support respecting `unpicklable` state ===
[{"py/object": "__main__.User", "username": "test1", "user_id": 1, "score": {"py/object": "numpy.float64", "dtype": "float64", "value": 1.23456}}, {"py/object": "__main__.User", "username": "test2", "user_id": 2, "score": {"py/object": "numpy.float64", "dtype": "float64", "value": 123.456}}]
[{"username": "test1", "user_id": 1, "score": 1.23456}, {"username": "test2", "user_id": 2, "score": 123.456}]
```

**Comment by Theelx** [comment]
Sorry for the late response, I got a notification about this but something came up and I forgot to answer.

I don't know much about the numpy handlers for jsonpickle, but my guess is that this is intended behavior. I'm running a test now to see if the json is actually unpicklable with the unpickleable option, it's possible that it's inserting extra data because it's not taking a fully simplified path.

**Comment by Theelx** [comment]
Oh never mind my previous comment, I'm not sure why I tried to test whether the json is unpickleable. I should take a nap ;)

It seems you're saying that problem is that with the default numpy support, jsonpickle is emitting unnecessarily complicated values by including the dtype of the array, when it shouldn't need to do that because it's already unpickleable, is that correct?

If that's what you're saying, I think it's actually better to include the dtypes by default, as it could help with debugging. `unpickleable` mode, as I understand it, is meant to provide a conceptually simpler output than normal jsonpickle for the purpose of debugging issues with the representation of data. By including dtypes, we can show that `score` is a numpy value (an instance of `numpy.float64`, as can be seen by 
```py
print(type(users[0].score)) # <class 'numpy.float64'>
```
rather than a normal float. After all, what you're proposing seems to just be to remove the information about score being a numpy value.

I think your idea has merit though, as not all people may be concerned with seeing that their `float` is actually a `numpy.float64` (since both are functionally quite similar). I'd be open to adding an option to `dumps` to strip numpy/pandas dtypes and other info from values, and just display the numbers as numbers (only when `unpicklable=True` of course). Does that seem like a decent option to you?

**Comment by stefan6419846** [comment]
Thanks for the quick reply.

It seems like you are mixing up some things about the *unpicklable* value here (see the following quote and the last paragraph of your last comment)? By default, we use `unpicklable=True` in `jsonpickle.pickler.encode`. I am asking about `unpicklable=False`, which should translate to *picklable*.

> It seems you're saying that problem is that with the default numpy support, jsonpickle is emitting unnecessarily complicated values by including the dtype of the array, when it shouldn't need to do that because it's already unpickleable, is that correct?

Yes, you are correct that the output is too complicated in this case in my opinion.

> After all, what you're proposing seems to just be to remove the information about score being a numpy value.

Yes, the "metadata" is not relevant in my case - I do not really care later whether we have a 64 bit NumPy value or just a 32 bit one or even a plain Python data type in the JSON output.

> I think your idea has merit though, as not all people may be concerned with seeing that their `float` is actually a `numpy.float64` (since both are functionally quite similar). I'd be open to adding an option to `dumps` to strip numpy/pandas dtypes and other info from values, and just display the numbers as numbers (only when `unpicklable=True` of course). Does that seem like a decent option to you?

I think you meant to write `unpickable=False` (see above)? I am not familiar enough with the `unpickable=False` option, so if a new option for stripping this (unnecessary) "metadata" makes more sense here than integrating it directly, this is no issue for me.

**Comment by Theelx** [comment]
Oh yes, you're right: I did mix up `unpickleable=True` and `unpicklable=False`.
> I think you meant to write unpickable=False (see above)? I am not familiar enough with the unpickable=False option, so if a new option for stripping this (unnecessary) "metadata" makes more sense here than integrating it directly, this is no issue for me.

Yep, this is what I meant. I'll see if adding your simpler numpy handler or adding a new flag to `encode` makes more sense, let me ask some people who use jsonpickle in production about their opinions. I'll try to add it within a few days.

**Comment by Theelx** [comment]
Because there are currently so many arguments to `encode`, I think I'll just add your generic numpy handler to the numpy extension, and add a mention to the documentation that if people don't care about including the dtype with numerical values, they can register your handler.
