### ISSUE TITLE
Next releases?

### ISSUE THREAD

**Issue by patou01** [jsonpickle/jsonpickle#416]
Hi,

I came across that my version of jsonpickle cannot unpickle frozen dataclasses, which has been fixed in https://github.com/jsonpickle/jsonpickle/commit/33921686003c534c51a16d71da605b030eee891b on 12th July (at least theoretically). But the latest tagged release you have is https://github.com/jsonpickle/jsonpickle/releases/tag/v2.2.0 on 10th May.
I see in the changelog that it is intended for V3.0.0, but I'm not sure when that comes out. 

How do you do your releases? Should I wait for 3.0.0 (any idea when?), or are you planning on automatic releases as some do (eg when all tests are passed after a merge on main they raise the version and release a tag)?

Alternatively I'll pin to the commit, just want to make sure I don't do something in a way that's not expected from your side.

Thanks :)

**Comment by Theelx** [comment]
I intend to release it before the second semester of my college begins on 2023-01-25. If it turns out that people need it sooner, I can probably release it around the end of November. Is that okay?

**Comment by patou01** [comment]
No worries, I don't "need" it, I can temporarily pin to a commit that works for me, don't rush. I was just wondering if it was intentional or not that there was a significant amount of commits on main since the last release, so I couldn't really figure out how you work.
I'll just make a note for myself that I need to update the requirements at some point.

Thanks for your work, and good luck with the studies!

**Comment by baldurmen** [comment]
Hello! I'm part of the of team that packages `jsonpickle` in Debian.

We're currently transitioning from Python 3.10 to 3.11 and since we currently package `2.0.0`, the testsuite is pretty broken for 3.11. I see you've fixed that in the main branch though, kudos!

The freeze (the period of time when packages can't be updated anymore) for the next stable version of Debian (Debian 12, Bookworm) is expected in February 2023. As such, if you could make a release as soon as you can, it would be very valuable to us, as it would let us update this package in Debian in time :)

Cheers, and thanks for your work on this.

**Comment by Theelx** [comment]
@baldurmen 3.0.0 has been released! https://pypi.org/project/jsonpickle/3.0.0/
