### ISSUE TITLE
cyfunction support

### ISSUE THREAD

**Issue by danbodily** [jsonpickle/jsonpickle#451]
I'm trying to jsonpickle a cythonized function.   There is a point at which the object is checked to choose an appropriate flattener.  If the thing to be encoded is indeed an  an 'object', an object flattener is used (see 801 and 807 in pickler.py _get_flattener function.  

cyfunctions are deemed objects(801),  they should be deemed functions (807).

**Comment by Theelx** [comment]
If I recall correctly, there was an issue with cyfunctions and pickling because there's something they didn't support a few years ago, I can check if that's been resolved. For lines 801 and 807, can you specify which version of the code you're using? This line doesn't seem like one you'd be referencing. https://github.com/jsonpickle/jsonpickle/blob/ef95ebcf56670c4967703c3357ea4c5abeead233/jsonpickle/pickler.py#L801C15-L801C15

**Comment by Theelx** [comment]
@davvid was this fixed with #477?

**Comment by davvid** [comment]
Yes, I believe those changes should have fixed this up.
