### ISSUE TITLE
Pandas series with object type get converted to strings

### ISSUE THREAD

**Issue by cliffckerr** [jsonpickle/jsonpickle#457]
This error is a slightly different take on https://github.com/jsonpickle/jsonpickle/issues/407 and https://github.com/jsonpickle/jsonpickle/issues/358.

My issue is that if a dataframe has a column of mixed type (e.g. `[4, 'foo']`), then it will be converted to strings on unpickling (e.g. `['4', 'foo']`):

```py
import pandas as pd
import jsonpickle as jp
import jsonpickle.ext.numpy as jsonpickle_numpy
import jsonpickle.ext.pandas as jsonpickle_pandas
jsonpickle_numpy.register_handlers()
jsonpickle_pandas.register_handlers()

# Create simple data frame of mixed data types
df1 = pd.DataFrame((
  a = [1, 2], 
  b = [4, 'foo']
))

# Convert to jsonpickle
string = jp.dumps(df1)
df2 = jp.loads(string)

# Show that it didn't work
print(df1.b.values)
print(df2.b.values)

assert df1.b[0] == df2.b[0] # False: the first is 4 and the second is '4'
```

I know there isn't an easy fix for this, but I'm hopeful that there's _some_ fix, since (at least in this case) the actual dataframe data looks a lot like JSON format already! In particular, one suggestion I have is that currently just a single `dtype` is stored per column:
```py
"meta": {"dtypes": {"a": "int64", "b": "object"}
```

My suggestion that I believe would solve this particular bug would be that if the `dtype` is `object`, to store a list (one for each element) instead. For example, in this case:
```py
"meta": {"dtypes": {"a": "int64", "b": {"object": ["int", "object"]}}
```

Personally, I also think storing `values` as a dict of lists (rather than as a string) would be more robust _and_ easier to read/interpret. I feel `pd.DataFrame.to_dict()` is already pretty close to what would be required!

**Comment by Theelx** [comment]
Hey, sorry for never responding. I just remembered this again given new activity on #407. I'm thinking out loud here, but I wonder if storing a primary non-container dtype for each column, then establishing a sort of MRO of dtypes to try converting each object to if the previous attempt fails could work. It would be extremely inefficient if none of the dtypes work, but the best case scenario is almost no perf penalty and relatively high usability, and the user could customize the order of type conversion attempts too.

**Comment by davvid** [comment]
That sounds like it could be a pretty viable solution. I appreciate your tenacity!

**Comment by davvid** [comment]
These fixes are all so good that I think I'm going to create a one-off `maint/v3` release branch and make two small tweaks to the current tree before tagging it as v3.4.0.

I'm going to remove the two breaking changes -- changing the `safe=True` default in the unpickler back to `safe=False` and I'm going to tweak the pickler so that it continues to emit tags.REPR for modules.

This effectively creates a v3 jsonpickle that's capable of reading the upcoming v4 version's data. In v4 we'll do the breaking change of emitting tags.MOD alongside the change to use `safe=True`.

I'll then merge that branch into main, but I won't take any of the source changes. Instead, I'll merge the changelog tweaks to insert the v3.4.0 release only. We can then release v4.0.0 with just the breaking changes.

I'll push the `maint/v3` branch and the merge into main up shortly. I'll wait until this weekend before doing the final v4 release in case there's any last minute tweaks that materialize before then. We'll probably end up deleting that branch before the end of the year; it should just be a temporary diversion.

**Comment by Theelx** [comment]
Sounds good. I do want to create something that can read versions of pandas dataframes encoded with previous versions of the code before this fix is released though.

**Comment by Theelx** [comment]
Oops, I didn't see that 3.4.0 was already released. I'm going to push a 3.4.1 version to add the backwards-compatible decoding real quick.
