### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [jsonpickle/jsonpickle#465]
Is it possible next time on release new version make the github release to have entry on https://github.com/jsonpickle/jsonpickle/releases? 🤔

I'm only asking because on the creation of a new GH release a notification is spread to all those whom have set in the web UI Watch->Releases.

My automation process uses those notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/ESSS/pytest-regressions/commit/bcd06142

**Comment by Theelx** [comment]
I think that's possible. I'll write a note to myself to read up on this when it's time to make a release, as I'm a bit time-crunched with the beginning of the Fall semester.

**Comment by kloczek** [comment]
Thank you 👍 😄 
If you are using github workflows to make new release in last URL is example what needs to be done to automatically create GH entry 😋

**Comment by kloczek** [comment]
Gr8 👍 😄

**Comment by davvid** [comment]
In case it helps, here's what we do in the garden project to create automatic github releases:

https://github.com/garden-rs/garden/blob/main/.github/workflows/release.yml#L1-L45

We could do something a lot more minimal -- i.e. *just* create the release and nothing more. When this runs it leaves the release in a pending state. I'll then login to github, go to the releases section, and then click "edit" on the new release so that it can be published.

The [garden](https://github.com/garden-rs/garden) release creates a bunch of binary artifacts and stuff, but for jsonpickle we can probably do much less.

**Comment by davvid** [comment]
@Theelx one last tweak before the v4.0.0 tag is pushed ~ I think I got the creation of github releases automated in #540.

I basically just copied this directly from the file above, but I trimmed it down and removed the `--draft` option so that we don't have to remember to login and click on the "Publish" button whenever we tag a new release.

If we merge this in then we should see the v4 tag create a github release automatically once I push that tag in.

After we merge this I'll create a new empty commit to demarcate the release (`git commit --allow-empty -m 'jsonpickle v4.0.0'`) and that'll be what gets tagged and deployed to pypi.

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by davvid** [comment]
Also, I don't want to steal your thunder on setting up an automatic GitHub release manager tool so by all means we can always replace what we have in #540 with something better that you might have cookin' sooner or later.

**Comment by Theelx** [comment]
> Also, I don't want to steal your thunder on setting up an automatic GitHub release manager tool so by all means we can always replace what we have in #540 with something better that you might have cookin' sooner or later.

Honestly I kinda gave up after working on it for a week, and I doubt I'd go back and finish it, so this is great. Thanks so much!

**Comment by davvid** [comment]
Woot! It worked :smile_cat: ~ https://github.com/jsonpickle/jsonpickle/releases/tag/v4.0.0
