### ISSUE TITLE
Dictionaries that use tuples as keys get the key restored as string not a tuple

### ISSUE THREAD

**Issue by dwagon** [jsonpickle/jsonpickle#502]
If you use a tuple as the key to a dictionary then jsonpickle encodes the tuple to a string, but doesn't decode it back to a tuple.

```
>>> d={(1,2): "foo"}
>>> jsonpickle.loads(jsonpickle.dumps(d))
{'(1, 2)': 'foo'}
```

jsonpickle==3.0.4
Python 3.12.3

**Comment by davvid** [comment]
Hi @dwagon -- we actually suppor this already, but support for non-string keys is opt-in.

```
>>> import jsonpickle
>>> d={(1,2): "foo"}
>>> jsonpickle.loads(jsonpickle.dumps(d, keys=True), keys=True)
{(1, 2): 'foo'}
```

Note how we have to pass `keys=True` when calling `dump()` and `loads()`.

We can reopen if this isn't working as expected, but I think this should do it.

If you could kindly share whether or not you saw the documentation for this feature that might help us improve the documentation.

**Comment by davvid** [comment]
> Why not have this as the default?

At this point it's mostly for historical and performance reasons. I think one of the rationales is that non-string keys are not natively supported by json, and it results in a slightly awkward-looking (to a human) json representation, so we try and be simpler by default.

If there's a strong push to make this the default it could be considered as part of a major version bump, but I'd have to hear from others for an opinion as to whether or not it's worth it.

Since this is a one-time learning cost for users, it might not really be worth the potential breakage it could cause for other packages so we tend to be careful and avoid breaking downstream users.

If @Theelx felt strongly about changing the default then I'd go along with it, but my default position is that it's fine as-is. I'm all ears, though.

Hope that makes sense, and thanks for the sug.
