### ISSUE TITLE
jsonpickle 0.8.0 fails to encode/decode exceptions with parameters

### ISSUE THREAD

**Issue by wiggin15** [jsonpickle/jsonpickle#96]
This code:

```
import jsonpickle

class SimpleException(Exception):
    def __init__(self, prop):
        self._prop = prop

print jsonpickle.decode(jsonpickle.encode(SimpleException(1)))
```

produces this exception:

```
Traceback (most recent call last):
  File "test_jsonpickle.py", line 7, in <module>
    print jsonpickle.decode(jsonpickle.encode(SimpleException(1)))
  File "build/bdist.macosx-10.8-x86_64/egg/jsonpickle/__init__.py", line 150, in decode
  File "build/bdist.macosx-10.8-x86_64/egg/jsonpickle/unpickler.py", line 25, in decode
  File "build/bdist.macosx-10.8-x86_64/egg/jsonpickle/unpickler.py", line 115, in restore
  File "build/bdist.macosx-10.8-x86_64/egg/jsonpickle/unpickler.py", line 153, in _restore
  File "build/bdist.macosx-10.8-x86_64/egg/jsonpickle/unpickler.py", line 171, in _restore_reduce
TypeError: __init__() takes exactly 2 arguments (1 given)
```

Reproduced on Mac, Redhat and Ubuntu. This is new in v0.8.0, v0.7.2 works fine.

**Comment by aldanor** [comment]
`jsonpickle` has no idea from an instantiated `SimpleException` object that it needs `_prop` to be passed as init args. This can be solved via calling the `super` constructor in `__init__`:

```python
In [21]: class SimpleException(Exception):
   ....:     def __init__(self, prop):
   ....:         super(SimpleException, self).__init__(prop)
   ....:         self._prop = prop
   ....:         

In [22]: jsonpickle.encode(SimpleException(1))
Out[22]: '{"py/object": "__main__.SimpleException", "py/reduce": [{"py/type": "__main__.SimpleException"}, {"py/tuple": [1]}, {"_prop": 1}, null, null]}'

In [23]: jsonpickle.decode(jsonpickle.encode(SimpleException(1)))
Out[23]: __main__.SimpleException(1)
```

**Comment by aldanor** [comment]
This is only a wild guess, but I can assume that the reason is that `jsonpickle` was doing something like this before (which wouldn't be quite right but would avoid calling init):
```python
obj = SimpleException.__new__(SimpleException)
obj._prop = 1
```
and now is trying to do something like this:
```python
obj = SimpleException.__init__(*args)
obj._prop = 1
```

**Comment by wiggin15** [comment]
AFAIK the proper way to call super in this case is without passing 'prop' to the parent's `__init__`... And then the problem is still there.

**Comment by aldanor** [comment]
If you call `super` with `prop`, the base exception class will store than in `.args` tuple and will return it in `__getnewargs__`, that's why it works.

**Comment by wiggin15** [comment]
I understand what you mean and you're right that passing prop to super fixes the problem. But:
1. It's not a must to pass all constructor arguments to super, and in fact I never do it for exceptions (I call super, but not with the arguments). I know there are others who don't.
2. there's a broken functionality here, >=0.8 is not backward compatible with <0.8.

I'm not sure if you are leaving this ticket open because you intend to fix this, or not.
Thanks.

**Comment by davvid** [comment]
I haven't closed this issue because I wonder if there's a good way to make this work.

The recent changes in this area were to support python's pickle protocol.  Perhaps what's happening is that since the built-in exception classes implement it, then your classes are now getting caught by that handling.

There's the custom handler approach, which is a little too much effort for most users, and then there's the possibility that we could expose the old method as a built-in custom handler that you can use for these classes.

I hate breaking backwards compatibility too. That stings and sorry for doing that. We should probably add tests for this use case.

There are a couple of ways we can handle this, unfortunately none of them are backwards-compatible, but I'm open to suggestions.

One option is to expose a custom handler so that users can register their class with that handler.  The old method can be provided as a built-in handler so that users can easily register their classes with it.

Another option is to expose a registration method that sets the jsonpickle protocol version (here we'd set it to v1)  for a class and then use that as the basis for fixing #4 .  The appeal of this option is that it allows for future evolution and helps avoid future breakage, but it means we have to keep various permutations of the code around purely for compat purposes, which is a maintenance burden. It would also be a more involved rework of the code, which is why that issue's been on the backburner for so long.

OTOH, class-level overrides of the pickle protocol sounds kinda scary to implement, and is the same amount of effort for the user (one-liner to register the class), and obviously I like deferring that old issue as long as possible, so exposing a custom handler might be the simpler solution for now.

Do any of these options sound good?

The hard part about is that we're trying to follow the pickle protocol spec which means we run into shortcomings like this where following the spec gives suboptimal behavior for some use cases.  We can't fix past mistakes but hopefully we can provide enough hooks and batteries included to make common cases easy to handle.

The detail about calling `super()` with/without props is an interesting note. That really hints that the python designers expect things to be used in a specific way, which has merits, but ultimately the library should be pragmatic and flexible.  I would have never stumbled upon that fix, so in the very least we should add a note about exceptions in our documentation to help others who may run into this same issue.

Users that can modify their classes may choose to change how they call the superclass's `__init__()` once they learn about this distinction.  Users that cannot modify their classes (maybe they're generated by a tool, or third-party) can possibly use a built-in handler.

**Comment by davvid** [comment]
This was probably fixed a long time ago.  The new commit added a unit test that guarantees this behavior.
